package burp;

import java.util.Map;

final class UiText {
    private static final Map<String, String> SPANISH = Map.ofEntries(
            Map.entry("English", "Inglés"),
            Map.entry("Spanish", "Español"),
            Map.entry("Language:", "Idioma:"),
            Map.entry("Configuration...", "Configuración..."),
            Map.entry("Tool Configuration", "Configuración de la herramienta"),
            Map.entry("Assign to Variable...", "Asignar a variable..."),
            Map.entry("Replace variables with their values...", "Sustituir variables por sus valores..."),
            Map.entry("Converts the placeholders in this request to plain-text values.", "Convierte los placeholders de esta petición en valores de texto."),
            Map.entry("Change variable folder...", "Cambiar carpeta de variables..."),
            Map.entry("Replaces matching placeholders from one folder with those from another.", "Sustituye los placeholders coincidentes de una carpeta por los de otra."),
            Map.entry("Replace variables with their values", "Sustituir variables por sus valores"),
            Map.entry("Preview of the values that will be written to the request:", "Vista previa de los valores que se escribirán en la petición:"),
            Map.entry("Replace values", "Sustituir valores"),
            Map.entry("Cancel", "Cancelar"),
            Map.entry("No defined variables can be replaced.\n", "No hay variables definidas que se puedan sustituir.\n"),
            Map.entry("The following will be replaced:\n", "Se sustituirán:\n"),
            Map.entry("(empty value)", "(valor vacío)"),
            Map.entry("\nThe following will be kept because they are not defined:\n", "\nSe conservarán porque no están definidas:\n"),
            Map.entry("\nThis action modifies the template open in Repeater.", "\nEsta acción modifica la plantilla abierta en Repeater."),
            Map.entry("The request does not contain placeholders with folders.", "La petición no contiene placeholders con carpeta."),
            Map.entry("Change variable folder", "Cambiar carpeta de variables"),
            Map.entry("Apply change", "Aplicar cambio"),
            Map.entry("Source folder:", "Carpeta origen:"),
            Map.entry("Target folder:", "Carpeta destino:"),
            Map.entry("No other folder is available as a target.", "No hay otra carpeta disponible como destino."),
            Map.entry("Select different source and target folders.", "Selecciona carpetas de origen y destino diferentes."),
            Map.entry("No changes", "Sin cambios"),
            Map.entry("There are no matching variables to replace.", "No hay variables coincidentes para sustituir."),
            Map.entry("Preview:", "Vista previa:"),
            Map.entry("There are no matching variables between these folders.", "No hay variables coincidentes entre estas carpetas."),
            Map.entry("\nThe following will be kept because they do not exist in the target folder:\n", "\nSe conservarán porque no existen en la carpeta destino:\n"),
            Map.entry("Assign to Variable", "Asignar a variable"),
            Map.entry("Folder:", "Carpeta:"),
            Map.entry("Ungrouped", "Sin carpeta"),
            Map.entry("Variable Name:", "Nombre de variable:"),
            Map.entry("Selected Value:", "Valor seleccionado:"),
            Map.entry("Match URL/Path (Regex):", "Coincidir URL/ruta (regex):"),
            Map.entry("Extract From:", "Extraer de:"),
            Map.entry("Response Body", "Cuerpo de respuesta"),
            Map.entry("Response Headers", "Cabeceras de respuesta"),
            Map.entry("Request Body", "Cuerpo de petición"),
            Map.entry("Request Headers", "Cabeceras de petición"),
            Map.entry("Regex Pattern (1 group):", "Patrón regex (1 grupo):"),
            Map.entry("Save this request to refresh token in the future", "Guardar esta petición para actualizar el token en el futuro"),
            Map.entry("Save Rule", "Guardar regla"),
            Map.entry("Please select or type a variable name.", "Selecciona o escribe un nombre de variable."),
            Map.entry("Variable names cannot contain '.'. Choose the folder separately.", "Los nombres de variable no pueden contener '.'. Elige la carpeta por separado."),
            Map.entry("Invalid selection range.", "Rango de selección no válido."),
            Map.entry("Error", "Error"),
            Map.entry("Enable Variable Replacement", "Activar sustitución de variables"),
            Map.entry("Enable Response Auto-Extraction", "Activar extracción automática de respuestas"),
            Map.entry("Automatically extracts variable values from responses to keep them updated in the background.", "Extrae automáticamente valores de variables de las respuestas para mantenerlos actualizados en segundo plano."),
            Map.entry("Refresh Status Codes:", "Códigos de estado de actualización:"),
            Map.entry("HTTP status codes (comma separated) that trigger an automatic token refresh (e.g., 401, 403).", "Códigos de estado HTTP (separados por comas) que activan una actualización automática del token (p. ej., 401, 403)."),
            Map.entry("Configure the interface language and the optional tag that uniquely identifies variable placeholders.", "Configura el idioma de la interfaz y la etiqueta opcional que identifica los placeholders de variables."),
            Map.entry("Drag to reorder or move variables between folders.", "Arrastra para reordenar o mover variables entre carpetas."),
            Map.entry("Search folders or variables", "Buscar carpetas o variables"),
            Map.entry("New Folder", "Nueva carpeta"),
            Map.entry("New Variable", "Nueva variable"),
            Map.entry("Delete Selected", "Eliminar selección"),
            Map.entry("Clear All", "Borrar todo"),
            Map.entry("Are you sure you want to clear all variables?", "¿Seguro que quieres borrar todas las variables?"),
            Map.entry("Confirm Clear", "Confirmar borrado"),
            Map.entry("Variable Value Editor (Paste long values here)", "Editor de valor de variable (pega aquí valores largos)"),
            Map.entry("Response Auto-Extraction Rule", "Regla de extracción automática de respuesta"),
            Map.entry("Enable auto-extraction for this variable", "Activar extracción automática para esta variable"),
            Map.entry("Regex (with 1 capture group):", "Regex (con 1 grupo de captura):"),
            Map.entry("Update Rule from Response...", "Actualizar regla desde respuesta..."),
            Map.entry("Token Refresh Request", "Petición de actualización del token"),
            Map.entry("Saved Request: None", "Petición guardada: Ninguna"),
            Map.entry("Refresh Variable", "Actualizar variable"),
            Map.entry("Send to Repeater", "Enviar a Repeater"),
            Map.entry("Edit Request", "Editar petición"),
            Map.entry("Use a tag in variable placeholders", "Usar una etiqueta en los placeholders de variables"),
            Map.entry("The tag must start with a letter and contain only letters, numbers, _ or -. ", "La etiqueta debe comenzar por una letra y contener solo letras, números, _ o -. "),
            Map.entry("Example: ", "Ejemplo: "),
            Map.entry("Tag:", "Etiqueta:"),
            Map.entry("Existing requests are not rewritten automatically. When tagging is enabled,", "Las peticiones existentes no se reescriben automáticamente. Al activar las etiquetas,"),
            Map.entry("only placeholders containing the configured tag are replaced.", "solo se sustituyen los placeholders que contienen la etiqueta configurada."),
            Map.entry("The tag must start with a letter and contain only letters, numbers, _ or -.", "La etiqueta debe comenzar por una letra y contener solo letras, números, _ o -."),
            Map.entry("Invalid Tag", "Etiqueta no válida"),
            Map.entry("Select a variable inside this folder to edit its details.", "Selecciona una variable de esta carpeta para editar sus detalles."),
            Map.entry("Select a variable to edit its details.", "Selecciona una variable para editar sus detalles."),
            Map.entry("Saved Request: Error parsing request data", "Petición guardada: Error al analizar los datos"),
            Map.entry("Double-click a variable to insert:", "Haz doble clic en una variable para insertarla:"),
            Map.entry("Search variables", "Buscar variables"),
            Map.entry("Double-click to expand or collapse", "Haz doble clic para expandir o contraer"),
            Map.entry("No value", "Sin valor"),
            Map.entry("Insert", "Insertar"),
            Map.entry("Refresh", "Actualizar"),
            Map.entry("Rename", "Renombrar"),
            Map.entry("Copy Placeholder", "Copiar placeholder"),
            Map.entry("Move to...", "Mover a..."),
            Map.entry("Delete", "Eliminar"),
            Map.entry("Variable Name", "Nombre de variable"),
            Map.entry("Current Value", "Valor actual"),
            Map.entry("Auto Extract?", "¿Extracción automática?"),
            Map.entry("Yes", "Sí"),
            Map.entry("No", "No"),
            Map.entry("Failed to send request to Repeater: ", "No se pudo enviar la petición a Repeater: "),
            Map.entry("Edit Saved Request - ", "Editar petición guardada - "),
            Map.entry("Host:", "Host:"),
            Map.entry("Port:", "Puerto:"),
            Map.entry("Save Changes", "Guardar cambios"),
            Map.entry("Copy to Clipboard", "Copiar al portapapeles"),
            Map.entry("Request copied to clipboard.", "Petición copiada al portapapeles."),
            Map.entry("Copied", "Copiado"),
            Map.entry("Failed to copy to clipboard: ", "No se pudo copiar al portapapeles: "),
            Map.entry("Invalid port number.", "Número de puerto no válido."),
            Map.entry("Host cannot be empty.", "El host no puede estar vacío."),
            Map.entry("Failed to parse HTTP request. Please verify the format.", "No se pudo analizar la petición HTTP. Comprueba el formato."),
            Map.entry("Fetching Response...", "Obteniendo respuesta..."),
            Map.entry("Failed to get response from server.", "No se pudo obtener una respuesta del servidor."),
            Map.entry("Fetch Error", "Error de obtención"),
            Map.entry("Error fetching response: ", "Error al obtener la respuesta: "),
            Map.entry("Highlight New Token - ", "Seleccionar nuevo token - "),
            Map.entry("Highlight/select the text you want to extract from the response below. The regex will be auto-generated.", "Selecciona el texto que quieres extraer de la respuesta. El regex se generará automáticamente."),
            Map.entry("Proposed Regex:", "Regex propuesto:"),
            Map.entry("Save Extraction Rule", "Guardar regla de extracción"),
            Map.entry("Please select some text to generate a regex.", "Selecciona algún texto para generar un regex."),
            Map.entry("Extraction rule updated successfully for variable: ", "Regla de extracción actualizada para la variable: "),
            Map.entry("Rule Updated", "Regla actualizada"),
            Map.entry("Refreshing...", "Actualizando..."),
            Map.entry("Refresh Success", "Actualización correcta"),
            Map.entry("Error during refresh: ", "Error durante la actualización: "),
            Map.entry("Refresh Error", "Error de actualización"),
            Map.entry("Folder", "Carpeta"),
            Map.entry("Variable", "Variable"),
            Map.entry("Invalid Name", "Nombre no válido"),
            Map.entry("Folder name:", "Nombre de carpeta:"),
            Map.entry("Variable name:", "Nombre de variable:"),
            Map.entry("A folder with this name already exists.", "Ya existe una carpeta con este nombre."),
            Map.entry("Duplicate Folder", "Carpeta duplicada"),
            Map.entry("Duplicate Variable", "Variable duplicada"),
            Map.entry("The placeholder could not be copied to the system clipboard.", "No se pudo copiar el placeholder al portapapeles del sistema."),
            Map.entry("Create another folder before moving this variable.", "Crea otra carpeta antes de mover esta variable."),
            Map.entry("Move Variable", "Mover variable"),
            Map.entry("Move variable to:", "Mover variable a:"),
            Map.entry("Rename Variable", "Renombrar variable"),
            Map.entry("Rename Folder", "Renombrar carpeta"),
            Map.entry("Delete Variable", "Eliminar variable"),
            Map.entry("Delete Folder", "Eliminar carpeta"),
            Map.entry("Move variables to Ungrouped", "Mover variables a Sin carpeta"),
            Map.entry("Delete folder and variables", "Eliminar carpeta y variables"),
            Map.entry("The following placeholders will change:\n", "Los siguientes placeholders cambiarán:\n"),
            Map.entry(" name cannot be empty.", " no puede tener un nombre vacío."),
            Map.entry(" names cannot contain '.'.", " no puede contener '.' en el nombre."),
            Map.entry("Variable '", "La variable '"),
            Map.entry("' already exists.", "' ya existe."),
            Map.entry("Copied ", "Copiado "),
            Map.entry(" to the clipboard.", " al portapapeles."),
            Map.entry("Placeholder will change:\n", "El placeholder cambiará:\n"),
            Map.entry("Renaming would conflict with '", "El nuevo nombre entraría en conflicto con '"),
            Map.entry("Delete variable '", "¿Eliminar la variable '"),
            Map.entry("Folder contains ", "La carpeta contiene "),
            Map.entry(" variables.", " variables."),
            Map.entry("Cannot move: '", "No se puede mover: '"),
            Map.entry("' already exists in Ungrouped.", "' ya existe en Sin carpeta."),
            Map.entry("Variable refreshed successfully: ", "Variable actualizada correctamente: ")
    );

    private UiText() {}

    static String get(UiLanguage language, String englishText) {
        return language == UiLanguage.SPANISH ? SPANISH.getOrDefault(englishText, englishText) : englishText;
    }
}
